version: '3.9'

services:
    worker:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            WEB_SERVER_HOST: 0.0.0.0
            WEB_SERVER_PORT: 8888
        ports:
            - "8888:8000"
        healthcheck:
            test: curl --fail http://0.0.0.0:8888/ || exit 1
            interval: 40s
            timeout: 30s
            retries: 3
            start_period: 60s
